# RPC Server Config
rpcserverip=127.0.0.1
rpcserverport=8000
rpc_server_weight=1

# Registry Server Config
registry_ip=127.0.0.1
registry_port=8001

# RPC Client Config
rpc_timeout_ms=5000
backup_request_ms=10
load_balancer=lalb
